version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /

    # Group packages into shared PR
    groups:
      application:
        patterns:
          - 'body-parser'
          - 'cookie-parser'
          - 'express'
          - 'express-*'
          - 'nhsuk-frontend'
          - 'nunjucks'

      build:
        patterns:
          - 'esbuild'
          - 'esbuild-*'
          - 'sass-embedded'

      lint:
        patterns:
          - '@eslint/*'
          - '@trivago/prettier-plugin-sort-imports'
          - '@types/*'
          - 'eslint'
          - 'eslint-*'
          - 'globals'
          - 'prettier'
          - 'typed-query-selector'
          - 'typescript-*'

      test:
        patterns:
          - 'supertest'

      tools:
        patterns:
          - '@inquirer/prompts'
          - 'browser-sync'
          - 'http-proxy-node16'
          - 'nodemon'
          - 'portscanner'
          - 'wait-on'

    schedule:
      interval: weekly
    cooldown:
      default-days: 4

    versioning-strategy: increase

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Group actions into shared PR
    groups:
      actions:
        patterns:
          - '*'

    schedule:
      interval: weekly
    cooldown:
      default-days: 4
