name: Code style checkes

on: pull_request

jobs:
  lint:
    name: Code style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      - name: Run code style checks
        run: npm run lint:prettier
